# Site
name: Blog de rutas de Orhithedog
description: Jekyll Theme for Blogging
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
paginate: 12

url: "https://orhithedog.github.io/"
baseurl:

# override the default url structure
# https://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

email: 'wowthemesnet@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'


# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'


# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives

# Other
markdown: kramdown
highlighter: rouge